### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by alancarlosml** [HijenHEK/gymania#1]
Hi, thank you for sharing your code.

I'm getting the following error: 

`"Connection id  sending message {"event":"pusher:error","data":{"message":"Could not find app key `gymania2020`.","code":4001}} "`

Do I need setup .env file with other information?

**Comment by alancarlosml** [comment]
And this other while running "npm run dev":

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../img/bg1.jpg' in 'C:\xampp\htdocs\academia\academia\gymania\resources\sass'
    at finishWithoutResolve (C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:293:18)   
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at processResult (C:\xampp\htdocs\academia\academia\gymania\node_modules\webpack\lib\NormalModule.js:676:19)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\webpack\lib\NormalModule.js:778:5
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:124:13)      
    at Object.loader (C:\xampp\htdocs\academia\academia\gymania\node_modules\css-loader\dist\index.js:154:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ERROR in ./resources/js/components/ActivitiesManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div>

ERROR in ./resources/js/components/AddPackage.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|     <div class="body form adding-packages">

```

**Comment by HijenHEK** [comment]
Hello ,
For the first one apparently you have run the app with the old JavaScript file since you said that you have run the ``$ npm dev `` after running the serve command and sure you need to add pusher vars , ex :

```
PUSHER_APP_ID=gymania
PUSHER_APP_KEY=gymaniaKey
PUSHER_APP_SECRET=gymaniaSecret
```

For the second issue i have just updated the repo . or go ahead and run 

    $ mv public/images public/img
    
I ll update the project soon .

**Comment by HijenHEK** [comment]
ps : run the  ` $npm run dev ` after setting up your pusher .env variables , since it uses process.env

**Comment by HijenHEK** [comment]
Last commit fixed the login issue .
The errors should be fix the way i mentioned before , they are not related to the main issue .

**Comment by alancarlosml** [comment]
Thank you so much!

Now I can log in.

But I cannot run `$ npm run dev`, because I am getting this error:

```
× Mix
  Compiled with some errors in 2.07s

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../storage/images/bg1.jpg' in 'C:\xampp\htdocs\academia\academia\gymania\resources\sass'
    at finishWithoutResolve (C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:293:18)   
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\xampp\htdocs\academia\academia\gymania\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at processResult (C:\xampp\htdocs\academia\academia\gymania\node_modules\webpack\lib\NormalModule.js:676:19)
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\webpack\lib\NormalModule.js:778:5
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\academia\academia\gymania\node_modules\loader-runner\lib\LoaderRunner.js:124:13)      
    at Object.loader (C:\xampp\htdocs\academia\academia\gymania\node_modules\css-loader\dist\index.js:154:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ERROR in ./resources/js/components/ActivitiesManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div>

ERROR in ./resources/js/components/AddPackage.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|     <div class="body form adding-packages">

ERROR in ./resources/js/components/CuActivity.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div class="body form">
|

ERROR in ./resources/js/components/CuCycle.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div class="body form">
|

ERROR in ./resources/js/components/CuMember.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|

ERROR in ./resources/js/components/CuPackage.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|     <div class="body form">

ERROR in ./resources/js/components/CyclesManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div>

ERROR in ./resources/js/components/DashboardCard.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|     <div class="card" :class="classes">
|         <slot></slot>

ERROR in ./resources/js/components/DashboardUi.vue 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
> <script>
|     export default {
|

ERROR in ./resources/js/components/MainBoard.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div  class="main-board"   v-if="loaded">
|   <div class="cards">

ERROR in ./resources/js/components/MembersManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div >

ERROR in ./resources/js/components/ModalUi.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template @done="hideModal" >
|     <div class="modal" @click="handle($event)" >
|     <font-awesome-icon  size="2x" @click="hideModal" color="white" class="icon icon--close" icon="times"></font-awesome-icon>
ERROR in ./resources/js/components/PackagesManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div>

ERROR in ./resources/js/components/SelectData.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|

ERROR in ./resources/js/components/SingleMember.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div class="single-member">
|     <div class="nav">

ERROR in ./resources/js/components/StaffManagement.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|
|   <div >

ERROR in ./resources/js/components/VueAlert.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <transition name="slide-fade">
|     <div v-show="active" class="alert translate" :class="className">

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 19 errors
```

**Comment by HijenHEK** [comment]
You are welcome but with all do respect please read the error message first . 
if you have no prior experience with webpack or laravel mix , this is not a good starting point , its still work in progress and i am not on it now . consider following and starring for future updates .
